### ISSUE TITLE
Use translations insead of Persian keywords or phrases

### ISSUE THREAD

**Issue by lnxpy** [AminAliH47/PicoSchool#5]
I've checked some views and noticed that you're using pure phrases like the exact Persian keywords in your `views.py` which is not recommended to be honest. A better approach is to use [Django Translations](https://docs.djangoproject.com/en/4.0/topics/i18n/translation/) instead. Using non-English keywords (specifically in the `.py` files) may cause Unicode issues on some system species and Python is actually working on that though.

Thanks for your cool project by the way. :heart: :)

**Comment by AminAliH47** [comment]
Hello there.
Thanks for reporting the issue.

The point is that this project is completely native to Iranian users and schools. Is there a specific reason we should use the Django i18n?

**Comment by lnxpy** [comment]
Django Translation System not only provides your project, translation compatibility but it allows you to use non-English keywords and phrases in your actual scripts. The majority of the current developments are the base fundamentals of future implementations and features. That's the main reason in fact.
